version: "3.8"
services:
  web:
    build: .
    command: gunicorn web.app:app --bind 0.0.0.0:8000 --workers 2
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
  bot:
    build: .
    command: python bot/bot.py
    env_file:
      - .env
    volumes:
      - ./:/app
