name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install deps
        run: |
          pip install -r bot/requirements.txt
          pip install -r web/requirements.txt
      - name: Lint (basic)
        run: |
          pip install flake8
          flake8 --max-line-length=120 || true
